apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "httpecho.fullname" . }}-httpecho
  labels:
    {{- include "httpecho.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: httpecho
  template:
    metadata:
      labels:
        app: httpecho
        {{- include "httpecho.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "httpecho.serviceAccountName" . }}
      containers:
        - name: httpecho
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "-text=$(HTTPECHO_MESSAGE)"
          envFrom:
            - configMapRef:
                name: {{ include "httpecho.fullname" . }}-config
            - secretRef:
                name: {{ include "httpecho.fullname" . }}-secret
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
