apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "httpecho.fullname" . }}-httpecho
  labels:
    {{- include "httpecho.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: httpecho
  template:
    metadata:
      labels:
        app: httpecho
        {{- include "httpecho.labels" . | nindent 8 }}
    spec:
      containers:
        - name: httpecho
          image: "{{ .Values.image.repository }}:{{ .Values.tag }}"
          args:
            - "-text=$(HTTPECHO_MESSAGE)"
          envFrom:
            - configMapRef:
                name: {{ include "httpecho.fullname" . }}-config
            - secretRef:
                name: {{ include "httpecho.fullname" . }}-secret
          ports:
            - containerPort: {{ .Values.service.port }}
